export const TOGGLE_SPEECH = 'TOGGLE_SPEECH';
export const TOGGLE_STUDENT = 'TOGGLE_STUDENT';
export const CLEAR_STUDENT = 'CLEAR_STUDENT';
export const PICK_STUDENT = 'PICK_STUDENT';
export const UPDATE_STUDENTS = 'UPDATE_STUDENTS';
export const UPDATE_SECTION = 'UPDATE_SECTION';