export default {
  TOGGLE_SPEECH: 'TOGGLE_SPEECH',
  TOGGLE_STUDENT: 'TOGGLE_STUDENT',
  PICK_STUDENT: 'PICK_STUDENT',
  SET_LOCAL_STORAGE: 'SET_LOCAL_STORAGE',
  LOAD_SECTION: 'LOAD_SECTION',
  UPDATE_STUDENTS: 'UPDATE_STUDENTS',
  UPDATE_SECTIONS: 'UPDATE_SECTIONS'
}